### ISSUE TITLE
Change Readme to include example that works with XIRR process

### ISSUE THREAD

**Issue by joffemd** [ahirner/TabulaRazr-OS#8]
It helps for demos to be able to use a PDF that can be successfully processed by the XIRR feature:  http://emma.msrb.org/ER588705-ER457598-ER860368.pdf

**Comment by wongalvis** [comment]
https://github.com/ahirner/TabulaRazr-OS/commit/63e5bc28ece2432aa953e58fe681fad90f5f35c6
